### ISSUE TITLE
UI very slow, performance problem

### ISSUE THREAD

**Issue by mocsa** [abstractspoon/ToDoList_Issues#58] opened 2015-09-01 19:01 UTC
After upgrading from 6.9 to 7.0 the UI of Todolist started to work VERY slow, for example:
* When I scroll the task list using the mouse (by dragging the scrollbar) the list does not scroll continuously but it is jumping in big increments.
* When I create a new task and enter the name and then press Enter it takes about half a second for the task to update its name from "Task" to the entered name.
* When I delete a task I can literally see the deleted task disappear and the tasks below scrolled upwards.

So in general every operation in the tree view works very slow. I have to wait for operations to complete because I can type faster than the UI can update. I do not have a similar problem in any other application I use, so it is probably not my PCs performance problem. I use a GeForce GT 640 graphics card, I'm not sure if it matters.
The above is valid for both the Task Tree and the List view. I use Win 8.1. My task database has 317 tasks, I hope it is not too big. I already upgraded to 7.0.1 but the problem is still there.
My general impression is that starting with 7.0 the developers started to use a new UI component to display the task list and it has major performance problems.

The Comments editor on the right of the task list is also very-very slow. I can easily type faster than the characters appear. So if I make a typo in my comment, I have to wait for the characters to catch-up with me, until I can see whether I really made a typo or not. This is true for both the Simple Text and the Rich Text editor.

I hope it is not my isolated problem, since as I see nobody reported it so far, although right after the upgrade the problem was very obvious and very annoying.

I'm not sure what other information to include. Please let me know what you need.

**Comment by Pierre-de-la-Verre** [comment] 2015-09-01 19:05
Thanks for your report.
Please add some information, as described here:
https://github.com/abstractspoon/ToDoList_Issues/blob/master/CONTRIBUTING.md

**Comment by mocsa** [comment] 2015-09-01 19:10
I already read that file. Exactly what information you mean? I included Windows and Todolist version. I cannot give you a better list of steps to reproduce the problem. The problem is always there. A screenshot wouldn't help for this report.
Regarding labels, I think I cannot add them. Let me know how shall I do it if it is not true.

**Comment by abstractspoon** [comment] 2015-09-02 00:13
@mosca : I can see that you are very angry and upset, but projecting those
feelings on to us will not help your cause.

If you cannot be more helpful then you cannot expect us to do anything.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by mocsa** [comment] 2015-09-02 08:10
Hi Dan,
Sorry if my report sounded harsh or aggressive. I can assure you I did not mean it that way, at all. You may have felt this attitude in my second comment, which was meant to be brief and to-the-point than aggressive.
Todolist is a fantastic program and I have been using it for a long time. Despite the reported problems above it is still usable, but I decided to report it (my first bug report on GitHub in my life), thinking that it could be an improvement for others, as well.
With all due respect, I still ask you (Pierre or Dan or to whomever it pertains) to please tell me specifically what other information do you need and I will be more than happy to give it. In my last comment I wanted to say that I tried to do my best in giving you all information in the mentioned file, so at the moment I cannot see what I missed. Therefore I need your help in this.
Best Regards,

**Comment by abstractspoon** [comment] 2015-09-02 09:05
1. Where is ToDoList installed on your machine?
2. Can you try closing TDL, renaming the preference file, and then restarting?
3. Can you try closing any background processes to see if they are having an influence?

**Comment by mocsa** [comment] 2015-09-02 10:02
Hi Dan,
Here are my quick answers:
1. It is not installed on my system partition but on a different partition where I have a lot of other utilities. I store my preferences in an INI file, so it is a "Portable" install.
2. I renamed ToDoList.ini in the program folder to ToDoList_old.ini. When I started todolist, it started with default settings. The tree view scrolls a bit smoother but still there is flickering as I scroll. Flickering means that the left part of the list (where the checkboxes and folder icons are) are quickly redrawn from time to time. Interestingly, the flickering also happens when I scroll very slow (let's say 5 lines per second).
The comments panel now works faster. I would say it is almost perfect. I cannot type faster than the characters appear and even when I hold down Backspace to delete a long multi-line text it works fast.
As the next step, I will gradually restore my Preferences to my old settings and keep an eye on any performance changes.
3. I closed down all foreground applications and my CPU load was 2-3%. I tried to scroll in the tree view and unfortunately I did not experience any positive change.
Regards,

**Comment by mocsa** [comment] 2015-09-02 11:24
I did some testing regarding flickering during scrolling. I tested the influence of
* selected fonts
* number of visible columns
* width of column area compared to the tree

For testing, the columns were visible to the right of the tree (default setting). Also, I used the default columns.

*Worst flickering when*
Column area is 80% width, tree is 20% width within the Task Tree tab. Flickering does not reduce even when only 1 column is shown on the right, compared to the default 13.

*Occasional flickering when*
Column area is less than 40% width within the Task Tree tab. Number of visible columns doesn't matter.

*No flickering but text of bottom task in the tree is sometimes smeared during scrolling when*
Column area is less than 30% width within the Task Tree tab. Number of visible columns doesn't matter.

Selected font does not seem to have any influence.

I hope this helps you to reproduce and pinpoint the problem.

Best regards,

**Comment by mocsa** [comment] 2015-09-02 15:45
If I have EnableLightboxMgr=1 in the Preferences section of my ToDoList.ini, then the Comments editor (both Rich and Simple text) becomes sluggish (I can type faster than it can update).

**Comment by abstractspoon** [comment] 2015-09-08 11:38
> If EnableLightboxMgr=0, the Comments editor becomes very fast, it updates instantly.

That's unexpected.

> Can it be that there was no INI conversion when I updated to 7.0

No. Conversions are only required when I do a major restructure of the ini file which last happened in 6.5.

**Comment by mocsa** [comment] 2015-09-08 18:19
To double-check my statement about the EnableLightboxMgr setting, I repeated the test a few minutes ago. I switched it to 1 in the INI file (after closing Todolist). Then I started Todolist and the Comments editor became slow. Switching it to 0 removed the problem. When the setting is 1, the editor prints the typed characters about 2-3 times slower than when the setting is 0.
By the way, what does this setting influence? Can I also change it from the Preferences menu? So far I always changed it in the INI file with a text editor.
All in all, it seems I can consistently reproduce this problem on my PC. Please let me know if you need me to test something further. I would be glad to help.

**Comment by abstractspoon** [comment] 2015-09-10 07:03
> Can I also change it from the Preferences menu?

Preferences > User Interface > General > Enable window fading when showing dialog boxes

> I did some testing regarding flickering during scrolling

Is it possible you have modified certain system settings that enable double-buffering?

**Comment by mocsa** [comment] 2015-09-10 11:29
Hi,
I tested the problem by switching the 'Enable window fading' option on and off in the Preferences window, and it slows down or speeds up the Comments window the same way when I changed this setting in the INI file.
I don't think I modified double-buffering settings. Can you tell me where this setting is. Is it an option of my graphics drivers? Or is it a standard setting in Windows?

**Comment by abstractspoon** [comment] 2015-09-11 00:13
> it slows down or speeds up the Comments window the same way

Is the problem visible for you if you just hold down say the 'w' key for a few seconds and then release? Does it take time for the app to catch up?

> Or is it a standard setting in Windows?

On reflection I think this is unlikely to be the cause (I'm probably the cause!) but it's worth checking out.

Control Panel > System > Advanced System Settings > Advanced > Performance

**Comment by mocsa** [comment] 2015-09-11 13:41
Yes, the speed difference is very noticeable even when I hold down one key only.
I found a screenshot of the Performance settings here:
http://cmdrkeene.com/blog/wp-content/uploads/2013/02/Performance-Options.png
Which of these shall I turn off? Which is related to double-buffering that you mentioned? Is it the Smooth-scroll listboxes?

**Comment by mocsa** [comment] 2015-09-11 13:50
Never mind, both problems can be experienced even if I switch off all options in the Performance settings.

**Comment by abstractspoon** [comment] 2015-09-12 08:38
Thx for confirming that. I will check this out on my VM of Windows 8.1.

Can you help me by adding these remaining issues to our new Google Group as I will be moving all issues there and removing this repo as soon as I can.

ie. One issue for "comments slowdown when 'Window fading' is enabled" and one for "Flickering"

**Comment by abstractspoon** [comment] 2015-09-14 01:12
Moved to Google group

**Closed by abstractspoon** 2015-09-14 01:12 UTC
Labels: Bug
