### ISSUE TITLE
Unable to complete multiple recurring tasks when 'Recreate Task' is enabled

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#52] opened 2015-08-20 21:51 UTC
TDL70
All OS

Unable to complete multiple recurring tasks when 'Recreate Task' is enabled

**Comment by abstractspoon** [comment] 2015-08-24 00:31
This is by design, so I've changed it to a feature request.

**Comment by abstractspoon** [comment] 2015-08-24 00:32
ps. Please don't put 'All OS' unless **you** have tested all OSes. This is a tag for me to use when I am satisfied it really does affect all OSes

**Comment by PatriceTorchet** [comment] 2015-09-12 09:25
OK no "All OSes" tag

**Comment by TonyGravagno** [comment] 2015-09-13 19:24
Dan, please ensure this is in your tasklist as an enhancement so we can close this for the migration to GG.

**Comment by abstractspoon** [comment] 2015-09-14 01:00
Moved to Google Group

**Closed by abstractspoon** 2015-09-14 01:00 UTC
Labels: 7.0.0, All OS Platforms, Feature Request
