### ISSUE TITLE
Issues with command-line switches

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#53] opened 2015-08-21 23:16 UTC
TDL v7.0.0 / Windows 8.1

1) From command-line none of the following change the value of the cost:

-cs 0
-cs 0.00
-cs "0"
-cs ""

2) After setting the completion date with the -cd switch, the -cd switch cannot be used again to remove the completion date.

**todolist -cd 8/18** ..... sets the date
**todolist -cd ""**   ....... doesn't clear it

3) Using -cd to set completion time without a date, defaults date to 0 = 12/30/1899. Same with -dd to set due time.

**todolist -cd 15:00**

4) The -d switch doesn't set Dependency values.

5) The -fr switch can only set one File Link value. If more than one -fr switch is present, the last value is added to the File Link list.

6) If the file in the list has the same name as an open .tdl file, the focus is reset to that tasklist. (Not 100% sure how to reproduce that one.

7) Similar to others above, the file link field cannot be cleared with the -fr switch. (Probably an enhancement?)

Haven't checked to see if any of these are regressions. Found the issues while writing the docs.

**Comment by abstractspoon** [comment] 2015-08-24 00:30
Hi Tony

Can you:

1. Add OS and TDL version info
2. Split off "5) If the file in the list has the same name..." into 6) because it is a separate issue.

**Comment by TonyGravagno** [comment] 2015-08-24 19:02
Updated original text with OS and TDL version, even though the ticket was labelled at entry time.
Broke combined item into 5,6,7.

**Comment by abstractspoon** [comment] 2015-08-25 06:17
> even though the ticket was labelled at entry time.

That's not the reason I want the info. Labels can be changed at any time.
More unlikely that the original text will be changed.

It's not a big ask really!

Rgds, .dan.g.

www.abstractspoon.com

**Comment by abstractspoon** [comment] 2015-08-26 01:53
Thx Tony

**Comment by TonyGravagno** [comment] 2015-08-26 02:39
I'm guessing that I'm going to find more issues as I go through the entire list alphabetically. Will add to the OP as time permits.

**Comment by abstractspoon** [comment] 2015-08-31 08:59
1, 2, 4, 5, 7 fixed in 7.0.1.

Note: For multi-value attributes (alloc to, category, dependency, file links, tags) prefix string with '+' to append items else they over-write whatever is there, To specify multiple items, use you regional list separator character (comma for US).

eg.

```-c bug``` will overwrite the selected task's category with 'bug'
```-c "bug, regression" will overwrite the selected task's category with 'bug' and 'regression'
```-c "+bug, regression" will append the selected task's category with 'bug' and 'regression'

**Comment by abstractspoon** [comment] 2015-08-31 10:44
I think 3) will need to be a feature request where we add ```-st/-dt/-ct``` to support setting the time independently of the date.

**Comment by abstractspoon** [comment] 2015-08-31 10:55
I can reproduce 6). Will fix for 7.0.2

**Comment by TonyGravagno** [comment] 2015-08-31 18:42
About 3, personally I don't think new switches are necessary. If the date is less than 1900 there's no way it's legit. So I'd suggest just taking the existing date and replacing the time component.

If you do want that as a feature request, I'll scratch 3 here and create a new ticket so that we can close this one.

Please re-assign back to me and I will update wiki based on all 7.0.1 changes.

**Comment by abstractspoon** [comment] 2015-09-02 09:31
> So I'd suggest just taking the existing date and replacing the time component.

Fair enough. I'll make this change for 7.0.2. And you can then add a comment about the restriction.

**Comment by abstractspoon** [comment] 2015-09-04 05:17
Hi Tony

Given the global historical use of <space> to delimiter values on the commandline, I'm going to change the specification of multiple categories, say, to use spaces instead of commas.

So my previous example becomes:

```-c bug``` will overwrite the selected task's category with 'bug'
```-c bug regression``` will overwrite the selected task's category with 'bug' and 'regression'
```-c +bug regression``` will append 'bug' and 'regression' to the selected task's category

This avoids the need for double quotes and avoid needing to handle differences in the user's locale-specific list separator.

Note: Individual values containing spaces would still need to be quoted.
Note: The ```-f``` switch that supports multiple filepaths separated by '|' will also be changed to use <space> but '|' will be be supported 'under the covers'. 

Sorry for any wiki work that will require changing.

**Comment by TonyGravagno** [comment] 2015-09-04 19:00
To confirm complete list replacement:

```
-c bug "next release" "another category" okToo andThis  
-fR "C:\path\file.ext" "D:\another path\file2.ext"
 ```

To confirm addition to existing lists:

```
-c +bug "next release" "another category" okToo andThis  
-fR +"C:\path\file.ext" "D:\another path\file2.ext" 
```

OR ?

```
-c "+next release" "another category" okToo andThis  
-fR "+C:\path\file.ext" "D:\another path\file2.ext" 
```

If someone tries this trick I'm guessing/hoping it won't work:

```
-c bug "next release" "another category" +okToo andThis  
-fR "C:\path\file.ext" "+D:\another path\file2.ext" 
```

**Comment by abstractspoon** [comment] 2015-09-05 01:35
> To confirm complete list replacement:

Yes.

> To confirm addition to existing lists:

The plus must be part of the first item, otherwise it will be treated as
part of any other item. My tests indicate that it can be inside or outside
quotes but must be joined to the first task. Perhaps specifying that it
must be inside the quotes (if present) would be best.

> If someone tries this trick I'm guessing/hoping it won't work:

Correct.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by TonyGravagno** [comment] 2015-09-06 21:07
Item 3 is still open in v7.0.2. Verifying and documenting other changes now.

3) Using -cd to set completion time without a date, defaults date to 0 = 12/30/1899. Same with -dd to set due time.

*todolist -cd 15:00*

**Comment by TonyGravagno** [comment] 2015-09-06 21:39
4) -d switch to set Dependency is still not working in 7.0.2.

```"C:\Users\tony\Downloads\ToDoList7\ToDoList.exe" -i "C:\Users\tony\Downloads\ToDoList7\ToDoList.ini" ".\Testing.tdl" -tid 7 -d 1```

The open/active TDL instance is apparently updated but not the Dependency field.

**Comment by TonyGravagno** [comment] 2015-09-06 21:45
Visual anomaly on -C:

```todolist -tid 1 -c foo``` That's fine.

No follow that with ```todolist -tid 1 -c +bar baz```

That changes the displayed value to only "bar, baz". But on opening the dropdown it shows foo is checked, and then resets the display to correctly show bar, baz, foo.

**Comment by abstractspoon** [comment] 2015-09-13 10:04
This issue was moved to abstractspoon/ToDoList_Wiki#27

**Closed by abstractspoon** 2015-09-13 10:04 UTC
Labels: 7.0.0, Bug, Wiki, Windows8
